url: https://y7kim.github.io
baseurl: https://projetowakanda.github.io/

# Site settings
title: Wakanda Project 
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Bianca Toller
  pic: 0
  position: Lead Developer
  social:
    - title: linkedin
      url: #

- name: FabioHCNobre
  pic: 0
  position: Desenvolvedor
  social:
    - title: linkedin
      url: #

- name: Gustavo Bione
  pic: 0
  position: Lead Developer
  social:
    - title: linkedin
      url: #

- name: Jonatas Souza
  pic: 0
  position: Negocio
  social:
    - title: linkedin
      url: #


- name: Rodrigo Rios
  pic: 0
  position: Lead Developer
  social:
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/projetowakanda

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty